theme: minima
title: welcome!
author: Swarita Kelwada
email: swarita.kelwada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my contaacts page

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Swarita # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
